eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
      
okta:
  oauth2:
    issuer: https://github.com/raghu111291/springboot/blob/main/application.yaml
    audience: api://default
spring:
  zipkin:
    baseUrl: http://zipkin-svc:9411
